name: Build OpenWRT Images
on: [push]

jobs:
    build:
        name: Prepare and build OpenWRT image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build target images
              run: |
                bash build_rpi4.sh

            - name: TAR output
              run: tar -cvf images.tar images

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: images
                path: images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v3
              with:
                name: images

            - name: Extract the image artifacts
              run: tar xf images.tar

            - name: Get the current date
              run: echo "NOW=$(date +%F)" >> $GITHUB_ENV

            - name: Create a release
              uses: "plu5/automatic-releases-with-sha-action@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: false
                title: "OpenWRT"
                automatic_release_tag: "OpenWRT"
                files: images/*